version: '3.7'

services:
  aqs-db:
    image: postgres
    container_name: aqs-db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - aqs_postgres_data:/var/lib/postgresql/data
    networks:
      - aqs-network

  aqs-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aqs-api
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
    restart: always
    ports:
      - ${API_PORT}:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - aqs-db
    networks:
      - aqs-network

networks:
  aqs-network:
    driver: bridge

volumes:
  aqs_postgres_data:
    driver: local
